### ISSUE TITLE
displaying song lyrics

### ISSUE THREAD

**Issue by chipunya** [chipunya/lyrics-search-JS#4]
tasks include: 
1. displaying song lyrics on click of the song chosen from the results displayed after searching. 
2. adding a functionality to display the search results by pages (like 10 results per 1 page)

**Comment by ray-nura** [comment]
I created the following functions: 
-fetched the data
-wrote a function to handle the search functionality: (user is able to search by any word)
- search results are displayed as a list of all matching artist names with song titles
